name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: Mod tidy
      run: |
        go mod tidy
        git diff --exit-code || exit 1

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
