name: Makefile

on:
  push:
    branches: [ main ]
  pull_request:
    branchs: [ '*' ]

jobs:
  latest:
    strategy:
      matrix:
        makerule: [ 'koversion', 'yttversion' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make bin/archy
      run: make bin/archy
    - name: make ${{ matrix.makerule }}
      run: make ${{ matrix.makerule }}
  devel:
    strategy:
      matrix:
        makerule: [ 'koversion', 'yttversion' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    # Use the installed Go version to download and install the latest 1.18
    # release candidate and replace our existing go with that one.
    - name: go1.18
      run: |
        go install golang.org/dl/go1.18rc1@latest
        go1.18rc1 download
        cp $(which go1.18rc1) $(which go)
        go version

    - name: make bin/archy-devel
      run: make bin/archy-devel
    
    - name: make ${{ matrix.makerule }}
      run: make ${{ matrix.makerule }}
