name: Makefile

on:
  push:
    branches: [ main ]
  pull_request:
    branchs: [ '*' ]

jobs:
  latest:
    strategy:
      matrix:
        makerule: [ 'koversion', 'yttversion' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make bin/archy
      run: make bin/archy
    - name: make ${{ matrix.makerule }}
      run: make ${{ matrix.makerule }}
  devel:
    strategy:
      matrix:
        makerule: [ 'koversion', 'yttversion' ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18.x

    - name: make bin/archy-devel
      run: make bin/archy-devel
    
    - name: make ${{ matrix.makerule }}
      run: make ${{ matrix.makerule }}
